### ISSUE TITLE
built in assertion guard for v14 metadata

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-api/polkadot-api#23]
Since we don't support metadata versions other than v14 (currently). Should we also export a v14 assertion guard so the user doesn't have to write it themselves? i.e.

```ts
import { metadata as $metadata } from "@unstoppablejs/substrate-codecs"
type Metadata = ReturnType<typeof $metadata.dec>["metadata"]

function assertIsv14(
  metadata: Metadata,
): asserts metadata is Metadata & { tag: "v14" } {
  if (metadata.tag !== "v14") {
    throw new Error("unreachable") // "this should never be hit since the decoded metadata is always v14"
  }
}
```

**Comment by josepot** [comment]
sure! just create a PR and add this into the `@substrate/bindings`. In fact, we have a `V14` type, so export it from there, for sure!
