### ISSUE TITLE
How can I throw a custom error from `onCreateTx`?

### ISSUE THREAD

**Issue by kratico** [polkadot-api/polkadot-api#301]
So far with `callback(null)` outputs `User cancelled tx`
But if I throw like this, the error can not be captured

![image](https://github.com/polkadot-api/polkadot-api/assets/1209171/343092d5-752a-4f97-9588-0fa3ffead933)

For more usage context see https://github.com/paritytech/substrate-connect/blob/fcb46fccb18ad8716b97b940b552c0cb6463dd2c/projects/wallet-template/src/background/createBackgroundRpc.ts#L78-L157

Also any advice on better api usage is welcome.

**Comment by josepot** [comment]
We could change the signature of the `callback` argument, so that if the `callback` receives an instance of an Error, then it propagates that error... Would that work for you?

**Comment by kratico** [comment]
it would work.
It will also require every `onCreateTx` fn body, that can potentially throw, to be wrapped in a `try/catch`, so the `catch` handle can invoke `callback(error)`.
Is that the desired api usage?
