### ISSUE TITLE
SyntaxError: The requested module '@polkadot-api/substrate-bindings' does not provide an export named 'v14'

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-api/polkadot-api#319]
Why do I get this error running decode viewer dapp? https://github.com/polkadot-api/polkadot-api/pull/317/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R92

```
import { v14 } from "@polkadot-api/substrate-bindings"
         ^^^
SyntaxError: The requested module '@polkadot-api/substrate-bindings' does not provide an export named 'v14'
```

**Comment by josepot** [comment]
Yeah! That example is quite outdated, thanks for pointing it out.
