### ISSUE TITLE
RpcError: Received duplicate hashes for the `chainHead_unpin` method

### ISSUE THREAD

**Issue by mutantcornholio** [polkadot-api/polkadot-api#320]
I'm getting a flacky error:
```
    RpcError: Received duplicate hashes for the `chainHead_unpin` method

      at onMessage (node_modules/@polkadot-api/substrate-client/src/client/createClient.ts:76:24)
      at onMessageProxy (node_modules/@polkadot-api/json-rpc-provider-proxy/src/get-sync-provider.ts:37:7)
      at _onMessageProxy (node_modules/@polkadot-api/json-rpc-provider-proxy/src/get-sync-provider.ts:92:11)
      at WebSocket._onMessage (node_modules/@polkadot-api/ws-provider/src/ws-provider.ts:31:43)
      at callListener (node_modules/@polkadot-api/ws-provider/node_modules/ws/lib/event-target.js:290:14)
      at WebSocket.onMessage (node_modules/@polkadot-api/ws-provider/node_modules/ws/lib/event-target.js:209:9)
      at Receiver.receiverOnMessage (node_modules/@polkadot-api/ws-provider/node_modules/ws/lib/websocket.js:1209:20)
      at node_modules/@polkadot-api/ws-provider/node_modules/ws/lib/receiver.js:608:16
```

It's quite hard to reproduce in my environment (around 5% fail rate), so collecting debug info is a bit hard.  
But from what I can tell, duplicate hashes find their way into this `blocks` variable here: https://github.com/polkadot-api/polkadot-api/blob/72750dae94bd93064fbc994cfd957eb17ea0a109/packages/client/src/observableClient/chainHead/chainHead.ts#L120

**Comment by josepot** [comment]
Thanks a lot for reporting this. I have also seen it a couple of times. However, I have never seen this against the light client, which makes me think that perhaps this could be an issue with the substrate nodes... Also, I looked into our code and the blocks that are being passed to the `unpin` function only come from 2 different sources:

1) The ones that we are unpinning internally because they are no longer being used. In this case we can't produce duplicates because we use a `Set` for computing this state.

2) The list of `prunnedBlocks` provided by the `finalized` event.

I suspect that this is an issue with the substrate nodes, that must be sending duplicate hashes in the `prunnedBlocks` list. However, we can only know for sure what it is that's happening if we are able to capture the messages that are being send/received with the RPC endpoint.

If you could please capture these logs and provide them to us that would be very helpful. You could use the following enhancer for capturing the logs:

```ts
interface Provider {
    send: (message: string) => void;
    disconnect: () => void;
}
type ConnectProvider = (onMessage: (message: string) => void) => Provider;

const withLogsProvider = (
  input: ConnectProvider,
  onMessage: (direction: 'in' | 'out', message: string) => void
): ConnectProvider => {
  return (onMsg) => {
    const result = input((msg) => {
      onMessage('in', msg)
      onMsg(msg)
    })

    return {
      ...result,
      send: (msg) => {
        onMessage('out', msg)
        result.send(msg)
      },
    }
  }
}
```

**Comment by mutantcornholio** [comment]
Here's the log file
[e2e.log](https://github.com/polkadot-api/polkadot-api/files/14571117/e2e.log)

Look for `0x9b4d1fe6e379060c21076bb6f07b4ae7882dd3ccc4c1a8ebd95083cd97c6cdcd` there. 

A note about prefixes:
```ts
function getLogWriter(prefix: string) {
  return (direction: string, line: string) =>
    fs.writeSync(logFile, `[${new Date().toISOString()}:${prefix}:${direction}] ${line}\n`);
}
// ...

  const relaychainClient = createClient(
    getChain({
      provider: withLogsProvider(WebSocketProvider("ws://127.0.0.1:9933"), getLogWriter("relaychain")),
      keyring: [],
    }),
  );

  const parachainClient = createClient(
    getChain({
      provider: withLogsProvider(WebSocketProvider("ws://127.0.0.1:9934"), getLogWriter("parachain")),
      keyring: [],
    }),
  );

```

**Comment by josepot** [comment]
> Here's the log file [e2e.log](https://github.com/polkadot-api/polkadot-api/files/14571117/e2e.log)

Amazing! Thanks a lot for this! This confirms what I already suspected:

> [2024-03-12T10:52:21.241Z:parachain:in] {"jsonrpc":"2.0","method":"chainHead_unstable_followEvent","params":{"subscription":"ET2KqKyRd0JHFBWg","result":{"event":"finalized","finalizedBlockHashes":["0x550d4b95ab01742eca096d1333d70af31398a0813ffcbdc967b508ca386919f1"],"prunedBlockHashes":["0x9b4d1fe6e379060c21076bb6f07b4ae7882dd3ccc4c1a8ebd95083cd97c6cdcd","0x5118a1c4dca06bed8c9bba158efb60d852c869222b5ef05251c6b276111d690b","0x9b4d1fe6e379060c21076bb6f07b4ae7882dd3ccc4c1a8ebd95083cd97c6cdcd","0xea75751787f32c9454f99a0b67ec8bf8f5cac034b6037aac6eaf70b86ffcef9a"]}}}

There are repeated items in the `prunedBlockHashes` entry, which confirms [this is an issue](https://github.com/paritytech/polkadot-sdk/issues/3658) on the polkadot-sdk.

**Comment by mutantcornholio** [comment]
The root cause aside, should we consider filtering the duplicates on the client, and not propagating the error? Make the library more resilient, instead of more fragile.

**Comment by josepot** [comment]
Masking upstream issues with a hack is IMO far from:

> Make the library more resilient, instead of more fragile.

If you want a temporary solution so that you can use the library while this is being fixed on polkadot-sdk, then I would suggest creating a connection-provider enhancer that transforms the messages that arrive with dups.

**Comment by mutantcornholio** [comment]
My reasoning is, not validating upstream responses has turned what considered an edge case on upstream into a recurring failure on client.  

But I can also see your point, we've all been there.

**Comment by josepot** [comment]
> not validating upstream responses

upstream responses are not user-inputs that require from validation. There is a spec for a reason.
