### ISSUE TITLE
Typings issues with AssetConvertion pallet

### ISSUE THREAD

**Issue by 0xKheops** [polkadot-api/polkadot-api#434]
Hey team,

I'm experiencing an invalid type issue when trying to pass arguments to `api.query.AssetConversion.Pools.getValue()`

It can be observed at https://github.com/0xKheops/papi-experiments/tree/747123de7ddc2d5f9748a49434bf4e718f907d98

Notice the code runs fine and expected output is correct, it seems to be just a typing issue.

equivalent call in pjs : 
![image](https://github.com/polkadot-api/polkadot-api/assets/26880866/351b30fd-ca7a-40ba-918e-3f9fe73e5dbb)

**Comment by josepot** [comment]
Please have a look at [this section of the docs ](https://polkadot-api.github.io/polkadot-api-docs/types#enum)🙏 

We will try our best to explain this better, but the gist of it is that inputing enums with Polkadot API shouldn't be done using plain js objects.

If you have a look at the types of `getValue` it shows this:

![image](https://github.com/polkadot-api/polkadot-api/assets/8620144/712912db-0d5f-4e5d-897b-573ab4818836)

which means that you must pass exactly an `Array` of 2 objects with the following shape:

```ts
{ parents: number, interior: XcmV3Junctions }
```

The thing is: how can you create an `XcmV3Junctions`? The recommended way is to simply import the `XcmV3Junctions` enum creator, like this:

```ts
import { XcmV3Junctions } from "@polkadot-api/descriptors"

XcmV3Junctions.Here() 
```

Once you know that, the DX is actually pretty amazing! Check this out:

https://github.com/polkadot-api/polkadot-api/assets/8620144/79163d0b-1dcb-4706-997f-5fc1f424912c

Alternatively you can use the `Enum` helper, like this:

https://github.com/polkadot-api/polkadot-api/assets/8620144/2f69b498-c01c-4ff9-a06b-93a05cc3fb19

**Comment by 0xKheops** [comment]
that's great, thanks!
