### ISSUE TITLE
Return Chain consts from client

### ISSUE THREAD

**Issue by wirednkod** [polkadot-api/polkadot-api#437]
It would be sure nice to be able to retrieve some constants such as the chain name, chain Id, symbol name (why not the whole chainspec with connected bootnodes)

Something equivalent to PJS API's :
```tsx
const chainName = await api.rpc.system.chain()
```

**Comment by josepot** [comment]
We should expose the info provided by the [`chainSpec` group of functions](https://paritytech.github.io/json-rpc-interface-spec/api/chainSpec.html).
