### ISSUE TITLE
call.getEstimatedFee() fails on rococo

### ISSUE THREAD

**Issue by 0xKheops** [polkadot-api/polkadot-api#464]
calling `call.getEstimatedFee()` on a transaction call fails on Rococo.
It works on most other chains, but not on Rococo which seems to be missing the TransactionPaymentCallApi api

Error message: `Execution failed: Other: Exported method TransactionPaymentCallApi_query_call_fee_details is not found`

**Comment by josepot** [comment]
fixed by #465
