### ISSUE TITLE
observable client error handling

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-api/polkadot-api#487]
I'm not an rxjs expert by any means but there appears to be no way to catch internal errors created by `chainHead$`, other than using the `onUnhandledError` global rxjs config. It also could be the case that all the observables created by `chainHead$` are hot (i have no idea), and since I didn't provide an error handler to each one of them, it bubbles up to the global error handler.

**Comment by josepot** [comment]
There shouldn't be a need for this. If you see this happening, that means that there is another bug. Therefore, it's that bug what should be solved.
