### ISSUE TITLE
Parallelize downloads when running papi update

### ISSUE THREAD

**Issue by 0xKheops** [polkadot-api/polkadot-api#511]
Currently in case there are multiple chains registered in `polkadot-api.json`, the `papi update` command processes chains one by one, sequentially.
Since each metadata download can take a pretty long time, the whole process can be very long. 
For example it took 2m20s on my last run (10 chains).

It would be nice if all downloads could be parallelized, to make runs faster.

**Comment by 0xKheops** [comment]
that was fast, thanks!

**Comment by josepot** [comment]
> that was fast, thanks!

yeah, it was a quick fix... Also, the fact that we were running `generate` for each key was problematic and further slowing down things. This should be fixed in `polkadot-api@0.7.1` 😉
