### ISSUE TITLE
Transaction might be sent to wallet multiple times

### ISSUE THREAD

**Issue by 0xKheops** [polkadot-api/polkadot-api#519]
Hello team,

I found a strange behavior while implementing a "follow-up flow" on pending transactions.

`call.signSubmitAndWatch()` returns an observable. If that observable is subscribed to more than once, it will send the transaction again to the wallet, resulting in multiple popups shown to the user.

This code opens 3 Talisman popups : 

```ts
const txw = call.signSubmitAndWatch(account.polkadotSigner, {
  mortality: { mortal: true, period: 64 },
});

const sub = txw.subscribe((x) => {
  logger.log("TX STATUS UPDATE", x);
  if (notify(x)) sub.unsubscribe();
});
const sub2 = txw.subscribe((x) => {
  logger.log("TX STATUS UPDATE", x);
  if (notify(x)) sub2.unsubscribe();
});
const sub3 = txw.subscribe((x) => {
  logger.log("TX STATUS UPDATE", x);
  if (notify(x)) sub3.unsubscribe();
});
```

Note: I'm using the basic client, not the getObservableClient one
Note 2: I have a workaround so no worries, this is just to let you know :)

**Comment by josepot** [comment]
> `call.signSubmitAndWatch()` returns an observable. If that observable is subscribed to more than once, it will send the transaction again to the wallet, resulting in multiple popups shown to the user.

This is actually the expected behaviour 😬 

By default observables are lazy and unicast. These Observables are no exception. Every time that you subscribe to the observable it will trigger its side-effects again. You could change this behaviour by making the resulting observable multicast (eg using the `share`, or the `shareReplay` operators).

However, now that I think about it... We should probably make the observables returned from `call.signSubmitAndWatch` shared and repayable by default 🤔. Let me think about it a bit more... I mean, but that actually seems super reasonable.

**Comment by 0xKheops** [comment]
Interesting :smile: 

Felt like a bug that it's subscribing to the observable that triggers sending the tx to the wallet, i thought it would be the call to the `signSubmitAndWatch` method.

**Comment by josepot** [comment]
> ```ts
> signSubmitAndWatch
> ```

yeah... It's tricky, but basically I think that you are right: it doesn't make sense that the observable that we provide in here is unicast. Also, all the other observables that we provide in the other top-level APIs are multicast and replayable. So, this one shouldn't be an exception. While we fix this, could you please try doing this?

```ts
const txw = call.signSubmitAndWatch(account.polkadotSigner, {
  mortality: { mortal: true, period: 64 },
}).pipe(shareReplay(1));
```

and let us know if that obserbable behaves the way that you expected it to behave? 🙏

**Comment by 0xKheops** [comment]
> i thought it would be the call to the signSubmitAndWatch method

Got another issue now, regarding this.

Could the signSubmitAndWatch method return a promise that would resolve once payload is signed ?
Otherwise there is no way for the dapp to know if user rejects the request, is it ?

**Comment by josepot** [comment]
> Otherwise there is no way for the dapp to know if user rejects the request, is it ?

If a user cancels, then the observable should error with a well-known error that has not yet been documented. If that's not the case, then that's a bug. But, I'm pretty sure that at the very least it errors, yeah.

**Comment by 0xKheops** [comment]
That works, thanks!

**Comment by carlosala** [comment]
We added a [comment in the docs](https://polkadot-api.github.io/polkadot-api-docs/typed/tx#signsubmitandwatch) and [in the jsdocs](https://github.com/polkadot-api/polkadot-api/blob/c0559a1c674b43ee95e88032552c85d7e185d931/packages/client/src/tx/types.ts#L157-L160) warning about this behaviour.
Thanks for the report!
