### ISSUE TITLE
Polkadot Asset Hub Types

### ISSUE THREAD

**Issue by tad3j** [polkadot-api/polkadot-api#523]
It seems like query/tx types are not yet available for Asset Hub, any plan to add support for that?

![image](https://github.com/polkadot-api/polkadot-api/assets/4150904/561821c8-e73f-45cc-8e7c-fedbe6d99115)

**Comment by carlosala** [comment]
Hi @tad3j, thanks for the report!
In fact, we do support AssetHub (and any other Substrate chain). I think there might be a misunderstanding about interacting with multiple chains. Could you share a more significant piece of code so we can look at it? I recommend our docs, especially the [codegen](https://polkadot-api.github.io/polkadot-api-docs/codegen) and [typed api](https://polkadot-api.github.io/polkadot-api-docs/typed) sections.

**Comment by tad3j** [comment]
Sorry, I missed the part where you can generate types via  `papi add --wsUrl` option (I only added `westend`).  After doing that and running `generate` I can see the types.

![image](https://github.com/polkadot-api/polkadot-api/assets/4150904/c3a64918-4c30-4a21-855e-a4b87a4b0a0e)

Thats awesome!

**Comment by carlosala** [comment]
That's great, I'm glad you solved it!
