### ISSUE TITLE
Create Transaction object from unsigned transaction hex string

### ISSUE THREAD

**Issue by tad3j** [polkadot-api/polkadot-api#527]
We have a use case where we need to serialize Transaction object (to hex) so that we can send it to another service for signing.

Serialization is already supported via code bellow:
```
const tx = api.tx.Assets.mint();
const encodedData = await tx.getEncodedData();
const hex = encodedData.asHex();
```

Inside another service we would like to create an instance of Transaction from this hex value so that we can sign it via `const signedTx = await tx.sign(signer);` and submit to blockchain.

In Polkadot SDK we do it via `const tx : Transaction = await api.tx(hex)`, would be nice if something similar could be added to this library as well.

**Comment by josepot** [comment]
I see, yeah, this makes sense! I'm going to add a new API directly into the client, which will allow you to do that, no problem!

**Comment by josepot** [comment]
@tad3j I just opened a PR to tackle this, could you please let me know if [these APIs](https://github.com/polkadot-api/polkadot-api/pull/554/files#diff-9ec9f81880c9d33ebf4b0a6da53cd67610283b24ee65ef41b7bde4a39fcebecfR170-R202) make sense to you? 🙏 

I've also update [one our our E2E ](https://github.com/polkadot-api/polkadot-api/pull/554/files#diff-c2dd184c24c2b5afbdd8497cd65cee21aa6e1788c7d7e9e7eddf45ea86570b79R116-R121)tests to use this new API.

**Comment by tad3j** [comment]
> @tad3j I just opened a PR to tackle this, could you please let me know if [these APIs](https://github.com/polkadot-api/polkadot-api/pull/554/files#diff-9ec9f81880c9d33ebf4b0a6da53cd67610283b24ee65ef41b7bde4a39fcebecfR170-R202) make sense to you? 🙏
> 
> I've also update [one our our E2E ](https://github.com/polkadot-api/polkadot-api/pull/554/files#diff-c2dd184c24c2b5afbdd8497cd65cee21aa6e1788c7d7e9e7eddf45ea86570b79R116-R121)tests to use this new API.

Sorry for late reply, I just noticed it.

Interface looks good to me. Is this still something that will get merged?
