### ISSUE TITLE
Typings problem on v0.11

### ISSUE THREAD

**Issue by 0xKheops** [polkadot-api/polkadot-api#580]
Hi all,

I'm having an issue trying to upgrade kheopswap to PAPI v0.11

I've been using a handy method pattern to get a typed api object based on a id since the very beginning, and this is not working after i upgrade to v0.11.

Not sure if this a typing bug/regression, a new limitation, or maybe a design problem on my side that got unveiled by this release.
Could you please have a look to help me find out why it's not working ?

Papi v0.11 bump PR is here : https://github.com/kheopswap/kheopswap/pull/1
⚠️ this is a new (public) repo! 

screenshot of the TS error from the 'provision-zombienet.ts', though these are all over the place : 
![image](https://github.com/user-attachments/assets/0aea4975-d995-4e01-94d5-66d3a13ed6e6)

getApi method is here : https://github.com/kheopswap/kheopswap/blob/eede053ca6422ad12cb365ed243e910f4ad261f0/scripts/src/common/getApi.ts

**Comment by voliva** [comment]
On first sight, I think it's related to a change I made to prevent users from using `compatibilityTokens` from one chain into another.

I'll investigate this, see if there's a way of letting join chains like your example, as I think it does make sense.

**Comment by voliva** [comment]
Will be released into 0.12, because we added a change in the CLI before so we can't raise it as a patch (and we're not doing release branches yet)
