### ISSUE TITLE
Add `Polkadot People Chain` as a known chain

### ISSUE THREAD

**Issue by Bullrich** [polkadot-api/polkadot-api#584]
Last week it was announced (https://github.com/polkadot-fellows/runtimes/issues/394) that the new `Polkadot People Chain` is live.

Could the new `people chain` be added to the [known chains](https://github.com/polkadot-api/polkadot-api/tree/main/packages/known-chains) directory?

Thank you.

**Comment by carlosala** [comment]
We have some pending additions as well, we will indeed tackle this soon.

**Comment by josepot** [comment]
> We have some pending additions as well, we will indeed tackle this soon.

I mean... This chain-spec is not even [present into the Polkadot-SDK repo](https://github.com/paritytech/polkadot-sdk/issues/5112), and I'm pretty sure that @Bullrich works in the same company that maintains said repo, so... 😅

**Comment by wirednkod** [comment]
IMO people chain is not a wellKnownChain. It is a good common parachain.
The best approach would be in parallel to the wellKnownChains (polkadot, kusama, westend) maybe it is a better approach to add the CommonGoodChains that will include the AssetHubPolkadot, AssetHubKusama, PeopleChains and any other chain that is a common good (also you prepare your structure for `Plaza` which would be very important for PAPI IMO).

**Comment by josepot** [comment]
> IMO people chain is not a wellKnownChain. It is a good common parachain.

what is the rationale for not treating system-chains as "well-known" chains? Why should a relay-chain be a well-known-chain and not its system-chains? I really am not following.

Anyways, PAPI has decided to export all the system-chains of polkadot, kusama, westend, rococo and soon enough Paseo... When they are exported there is no mention to the concept "well-known-chain", that is just an internal implementation detail. 

They all get exported from `polkadot-api/chains/RELAYCHAIN_CANONICAL_NAME_SYSTEM_CHAIN_CANONICAL_NAME`.

I really don't get your point

**Comment by wirednkod** [comment]
> what is the rationale for not treating system-chains as "well-known" chains? Why should a relay-chain be a well-known-chain and not its system-chains? I really am not following.

Just an opinion. Any approach would do.

Also please remove rococo since it is decided to be deprecated as a chain from Polkadot testnets

**Comment by josepot** [comment]
> Also please remove rococo since it is decided to be deprecated as a chain from Polkadot testnets

Once its finally deprecated (not the case ATM) and Paseo is at pair, then we may remove it. We can't do it before then. Also, there is no harm in keeping it, as it doesn't add any weight into your bundle-size if you don't import it...

**Comment by bkchr** [comment]
@Bullrich can you not just move ahead with the chainspec for now?

**Comment by carlosala** [comment]
We added the chainspec, following https://github.com/paritytech/polkadot-sdk/pull/5124.
Thanks for the idea!
