### ISSUE TITLE
Generated API docs based on metadata

### ISSUE THREAD

**Issue by mutantcornholio** [polkadot-api/polkadot-api#585]
_Creating this as a counterpart of our issue in Parity_ 

PJS has [these docs](https://polkadot.js.org/docs/polkadot/runtime), which are super useful. Not without it's downsides, but still. 

Let's create the same for PAPI.  

I did some digging, and had a couple of discussions with @josepot already, so we kinda have a plan.  
In order to display correct types, we'll need a special metadata builder for docs, similar to [types-builder](https://github.com/polkadot-api/polkadot-api/blob/21165d7036a9832b146891be2a891968e4954492/packages/codegen/src/types-builder.ts), that would return denormalized types, suitable for documentation. 

So, something like
```ts
limited_teleport_assets: TxEntry
(data: {
    dest: XcmVersionedLocation;
    beneficiary: XcmVersionedLocation;
    assets: XcmVersionedAssets;
    fee_asset_item: number;
    weight_limit: XcmV3WeightLimit;
}) => Transaction<...>
```
instead of 
```ts
TxDescriptor<Anonymize<I5gi8h3e5lkbeq>>;
```

From that, we can take different routes on building the docs themselves.  

I've tried using template engine to build `.md`s for `vocs`; it kinda worked, but ugly in implementation, and isn't very good for API reference-style docs. It doesn't allow navigating through types, search is a mess, TOC needs some custom work to look usable.  
[Here](https://github.com/polkadot-js/api/blob/bfb92e6d8b4c322eecf222fc2003ed0d1be3b9cc/packages/typegen/src/metadataMd.ts)'s how PJS approaches this.

I propose building typescript files which would be fed to TypeDoc. It's better suited for the job, providing type navigation out of the box and better stucture.  
For this we'll (probably) need to reinvent [generate-descriptors](https://github.com/polkadot-api/polkadot-api/blob/affa67402ff441bb4a2f94befa593d7ebfdedd79/packages/codegen/src/generate-descriptors.ts), although some parts could probably be reused.  

Both ways imply some heavy templating, but doesn't look like there's a better way.  

I'll do the fronend part myself, but I'll probally need help with metadata builder.

**Comment by mutantcornholio** [comment]
A prototype for Storage queries
![Screen Shot 2024-07-30 at 18 00 54](https://github.com/user-attachments/assets/08a2d856-9da9-4a9a-a245-209c3bc9e6f7)
[docs.tar.gz](https://github.com/user-attachments/files/16431182/docs.tar.gz)

**Comment by jak-pan** [comment]
Super useful! I would propose an upgrade -> this is just scraping metadata from node with pjs (old ones) and generating super simple website based on this but with papi it could be much more powerful... We could have submission, data explorer etc :P similar to polkadot.js but better... 

https://apidocs.bsx.fi/Basilisk/pallets/Balances/storage/Locks

**Comment by josepot** [comment]
> Super useful! I would propose an upgrade -> this is just scraping metadata from node with pjs (old ones) and generating super simple website based on this but with papi it could be much more powerful... We could have submission, data explorer etc :P similar to polkadot.js but better...
> 
> https://apidocs.bsx.fi/Basilisk/pallets/Balances/storage/Locks

I love the idea! Yes! Absolutely! we should do this!

I noticed that the [Basilisk-ui](https://github.com/galacticcouncil/Basilisk-ui) repo is unlicensed... Would you be cool with us forking it and improving it to add these features, plus make it work with any Polkadot-SDK chain? 🙏  We would, of course, credit the original project.

**Comment by jak-pan** [comment]
> > Super useful! I would propose an upgrade -> this is just scraping metadata from node with pjs (old ones) and generating super simple website based on this but with papi it could be much more powerful... We could have submission, data explorer etc :P similar to polkadot.js but better...
> > https://apidocs.bsx.fi/Basilisk/pallets/Balances/storage/Locks
> 
> I love the idea! Yes! Absolutely! we should do this!
> 
> I noticed that the [Basilisk-ui](https://github.com/galacticcouncil/Basilisk-ui) repo is unlicensed... Would you be cool with us forking it and improving it to add these features, plus make it work for any Polkadot-SDK chain? 🙏 We would, of course, credit the original project.

Everything we do is OSS... Feel free to fork anything! We'd be up to help make it nicer once you get it running.

**Comment by mutantcornholio** [comment]
> Super useful! I would propose an upgrade -> this is just scraping metadata from node with pjs (old ones) and generating super simple website based on this but with papi it could be much more powerful... We could have submission, data explorer etc :P similar to polkadot.js but better...

So if the question is generating docs for any chain, then it's exactly what I'm aiming for.  
But, using the same TS types that PAPI generates, not the plain metadata stuff.  

Generating HTML was my first attempt at it, and I kinda got similar results to [generated PJS docs](https://polkadot.js.org/docs/polkadot/storage#offences). Generating TS seems a bit more promising, for the reasons mentioned above.  

"PAPI apps", however, sounds like a completely different project: instead of generating special denormalized types for docs, it would just simply use papi client-side (possibly, generating descriptors in runtime) and allow interactions to live chains.  
It definitely sounds like a cool project to work on though.

**Comment by mutantcornholio** [comment]
Here's an updated version with Constants / Types / etc., 
[doc.tar.gz](https://github.com/user-attachments/files/16453807/doc.tar.gz)
![Screen Shot 2024-08-01 at 11 11 50](https://github.com/user-attachments/assets/5ffa934d-aef4-4e6e-8470-a9fb13d01392)

It still lacks calls, runtime calls and events sections, as they contain circular types, and I'm waiting for @josepot on his idea how to handle them.

**Comment by rzadp** [comment]
Great work @mutantcornholio!

I tried looking at some types that I've been using, and this already looks useful to me.

For example, I really could use `ReferendumInfoFor` type doc in the past - it's quite a complex return type and I didn't find it documented anywhere!

<img width="520px" src="https://github.com/user-attachments/assets/6091228e-7a6b-4cc7-9b51-b8c675c43c73"/>

---

> Other than that, I'm open to feedback now

Sure, here it goes :D

---

1. The type in the screenshot above is not exactly correct and it can be misleading.

`deciding` can be a `null`, and if it's not, `confirming` inside of it can be `null`. This is pretty important, this determines the state of an ongoing referendum (one of: preparing/deciding/confirming).

For example, referendum 1042 on Polkadot right now:

![Screenshot 2024-08-02 at 11 44 07](https://github.com/user-attachments/assets/e055bfd3-75b8-4dc6-9f99-bfbcb4edf9e3)

---

2. Is the `StorageDescriptor`, `PlainDescriptor`, etc here to stay, or will we try to get rid of them? Would be nice to get rid of them I guess. (stop displaying to the user)
---

4. `Utility.batchedCallsLimit` is snake case, not like the others - weird?

<img width="420px" src="https://github.com/user-attachments/assets/05e82625-24ef-47a5-bf8d-7d7bf1215210"/>

---

5. Unnecessary `PapiTypes.` prefix

<img width="420px" src="https://github.com/user-attachments/assets/4502174f-4016-40ba-9188-18f45da251aa"/>

`Enum` is shown as `PapiTypes.Enum` which I think would look better shortened. Same as `PlainDescriptor` is NOT displayed as `PapiTypes.PlainDescriptor`.

---

6. `PapiTypes` has an empty index.

![Screenshot 2024-08-02 at 12 00 14](https://github.com/user-attachments/assets/7c779d17-4232-4fae-a50b-467f195d37f8)

But it has stuff used all over like `PlainDescriptor` or `Enum` - shall we display them here in an index? Or remove this section from the sidebar, if it's empty.

---

7. Undefined curves.

Those curve types are displayed as undefined, which is wrong.
![Screenshot 2024-08-02 at 12 01 32](https://github.com/user-attachments/assets/bca48cce-f90d-4847-ae6a-885c9f64e8f1)

**Comment by mutantcornholio** [comment]
> 1. The type in the screenshot above is not exactly correct and it can be misleading.
> 
> `deciding` can be a `null`, and if it's not, `confirming` inside of it can be `null`. This is pretty important, this determines the state of an ongoing referendum (one of: preparing/deciding/confirming).
> 

Yup, sounds like a bug on my end, the types in actual PAPI descriptors are correct.  
<img width="715" alt="Screen Shot 2024-08-02 at 13 16 26" src="https://github.com/user-attachments/assets/b2cf678b-1d7c-4c7b-89ce-e95bf14d2404">
I'll probably need to invest in tests later on

<hr />

> 2. Is the `StorageDescriptor`, `PlainDescriptor`, etc here to stay, or will we try to get rid of them? Would be nice to get rid of them I guess. (stop displaying to the user)


I'm not sure... It's what these types _are_, as they tell how could they be used. 
On one hand, I could frame it more in the way how PJS does it [in their docs](https://polkadot.js.org/docs/polkadot/storage#childbountiesu32-u32-optionpalletchildbountieschildbounty), but at the same time, I need to produce valid TS types. How would you like to see them?  
So for storage entries, I'll need to describe every item that can be queried like
```ts
const result: ReturnType = api.storage.Pallet.StorageEntry.getValue(args: Args)
```
`StorageDescriptor<ReturnType, Args>` kinda does it...
<hr />

> 4. `Utility.batchedCallsLimit` is snake case, not like the others - weird?

Weird indeed, but not the issue with the generated docs
<img width="591" alt="Screen Shot 2024-08-02 at 13 09 45" src="https://github.com/user-attachments/assets/5425f863-6490-41c7-9ebb-e8edbe0392b0">

<hr />

> 5. Unnecessary `PapiTypes.` prefix

> `Enum` is shown as `PapiTypes.Enum` which I think would look better shortened. Same as `PlainDescriptor` is NOT displayed as `PapiTypes.PlainDescriptor`.

I'll see if I can get rid of `DescriptorTypes` and `PapiTypes` in docs, but still have those grouped somehow, with an indication on where to import them from.

<hr />

> 6. `PapiTypes` has an empty index.
> huh, that's not what I see locally. Will doublecheck later

<img width="704" alt="Screen Shot 2024-08-02 at 13 12 20" src="https://github.com/user-attachments/assets/2f7eebc9-0150-4826-9b36-ce1b8acd3541">

<hr />
 
> 7. Undefined curves.
> 
> Those curve types are displayed as undefined, which is wrong. ![Screenshot 2024-08-02 at 12 01 32](https://private-user-images.githubusercontent.com/12039224/354557066-bca48cce-f90d-4847-ae6a-885c9f64e8f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTY5MTcsIm5iZiI6MTcyMjU5NjYxNywicGF0aCI6Ii8xMjAzOTIyNC8zNTQ1NTcwNjYtYmNhNDhjY2UtZjkwZC00ODQ3LWFlNmEtODg1YzlmNjRlOGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDExMDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YTMyN2EzYzI5Yjg4ZWEwNDY1Njk2MzY4NTBiZDc5MTU2YjY2ZTc0YWEwY2M2ZTcxMTNjMDBhNTBhYTJiMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iMBYdcGw_7VaD6t3VeOKiCp2RffHTszZhWVZdkwm1wo)

Good catch, definitely a bug on my end!

Thanks for the feedback, @rzadp! ❤️

**Comment by mutantcornholio** [comment]
[doc.tar.gz](https://github.com/user-attachments/files/16511365/doc.tar.gz)

@rzadp here's an update

So I fixed the bugs, and temporarily removed PapiTypes (it still might appear on some statically written comments). This leads to types like `StorageDescriptor` and `SS58String` not being links, but maybe making them so is actually more misleading than not defining them (as they aren't a part of descriptors). WDYT?

**Comment by rzadp** [comment]
> This leads to types like `StorageDescriptor` and `SS58String` not being links, but maybe making them so is actually more misleading than not defining them (as they aren't a part of descriptors). WDYT?

Yes, that is more misleading. I thought we would remove those altogether, same as you would use `Awaited<>` to get rid of a `Promise<>` and get to a type you care about. But that's just my feeling, perhaps I'm misguided. As you said before, it's what these types are, as they tell how could they be used. So perhaps we better get back to the previous approach - or maybe we get some more opinions on this.

Besides, I see the fixed bugs, nice. Here are some more potential issues:

1. Those enums look wrong:

![Screenshot 2024-08-06 at 21 18 32](https://github.com/user-attachments/assets/b8dc6595-2658-42c7-91f6-5f04b7334a16)
![Screenshot 2024-08-06 at 21 26 19](https://github.com/user-attachments/assets/54918e09-631d-4487-93f3-611c492bc399)

---

2. Lots of empty `Index` sections. Can we omit sections that have no contents?

![Screenshot 2024-08-06 at 21 26 35](https://github.com/user-attachments/assets/451fbf12-65d4-40b7-955c-913167de3bd3)

3. Some leftover

![Screenshot 2024-08-06 at 21 26 00](https://github.com/user-attachments/assets/b0e028b9-a8aa-45d0-9e9d-8c444efa000f)

**Comment by mutantcornholio** [comment]
> Those enums look wrong:

That's how Enums in PAPI are defined. 

```ts
type Enum<T extends {}> = {
    [K in keyof T & string]: {
        type: K;
        value: T[K];
    };
}[keyof T & string];
```

Some can have values, and some are just names:
```ts
export type DispatchRawOrigin = Enum<{
    "Root": undefined;
    "Signed": Anonymize<SS58String>;
    "None": undefined;
}>;
```

> Lots of empty `Index` sections. Can we omit sections that have no contents?

They aren't empty 😅
Just for some reason they've used `<h3>` for both levels of headings
![Screen Shot 2024-08-07 at 09 21 11](https://github.com/user-attachments/assets/f12af0f1-10ef-4d6e-9777-7eb9b2dd7a6e)

"Type Aliases" is a section of index (because, only link to items are listed)

> Some leftover

That's not a leftover!
I genuinely don't know how to use these errors yet. Waiting for PAPI team to update the docs first (there's no "errors" section in papi.how)

**Comment by mutantcornholio** [comment]
Here's another update, this time the docs are complete, with events, runtime apis and transactions:
[doc.tar.gz](https://github.com/user-attachments/files/16867413/doc.tar.gz)

**Comment by rzadp** [comment]
One note from me, about those references:

![Screenshot 2024-09-05 at 17 15 54](https://github.com/user-attachments/assets/29c16d9c-fafc-4e4e-bfe9-8b527364d3b0)

For the user browsing this site, this information is meaningless, because they cannot open this file.
So I think it would be better to remove those references.

**Comment by mutantcornholio** [comment]
> For the user browsing this site, this information is meaningless, because they cannot open this file. So I think it would be better to remove those references.

Good point, I'll hide it with custom css probably

**Comment by mutantcornholio** [comment]
Going beta! https://papi-how.ghp.mcornholio.ru/getting-started

PR to docs https://github.com/polkadot-api/polkadot-api-docs/pull/29

**Comment by KarimJedda** [comment]
This is excellent, thanks for making it @mutantcornholio .

**Comment by mutantcornholio** [comment]
The docs are live on https://chains.papi.how/!

I'll do the forum post announce soon, and this chapter will be closed :)
