### ISSUE TITLE
Missing/incompatible ESM typings for `polkadot-api/polkadot-sdk-compat`

### ISSUE THREAD

**Issue by rflechtner** [polkadot-api/polkadot-api#603]
I'm facing typescript issues when trying to import `polkadot-api/polkadot-sdk-compat` as instructed in the documentation:

```typescript
import compatEnhancer from "polkadot-api/polkadot-sdk-compat";

// Connect to kilt spiritnet.
const client = createClient(
  compatEnhancer(WebSocketProvider("wss://kilt.ibp.network"))
);
```
Typescript v `5.3.5` raises an issue reading as follows:
```
index.ts:8:3 - error TS2349: This expression is not callable.
  Type 'typeof import("[...]/node_modules/@polkadot-api/polkadot-sdk-compat/dist/index")' has no call signatures.

8   compatEnhancer(WebSocketProvider("wss://kilt.ibp.network"))
```

My tsconfig is:
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```
with `"type": "module"` set on the `package.json` to enforce ESM mode compilation mode.

I suspect that this may have to do with the fact that Typescript definitions are currently only provided for the commonjs build of the polkadot-api libraries; esm variants (located in `/dist/esm/`) do not have their own typings, leading to tsc falling back onto cjs types, but AFAIK type definitions generated in CJS mode are not guaranteed to work for ESM.

It could also have to do with call signatures on top-level exports not being supported in ESM (https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#the-impact-of-es6-on-module-call-signatures), although I have explicitly enabled `esModuleInterop`.

Note that this is a typescript-only issue; ignoring it with a `@ts-ignore` directive leads to my code running without issues.

**Comment by carlosala** [comment]
This was solved in #614. We changed that default export to be a named export `withPolkadotSdkCompat`. It'll be available starting the next release.
Thanks for the report!
