### ISSUE TITLE
Internal RPC error when trying to use Polkadot-People chain with light client

### ISSUE THREAD

**Issue by tien** [polkadot-api/polkadot-api#616]
I've got internal RPC error when using a smoldot client initiated with the chainspec exported by `@polkadot-api/known-chains` for Polkadot-People chain. Everything works fine when using a WS connection.

**Comment by tien** [comment]
Dug into how smoldot work and found that there's a `potentialRelayChains` field that you need to pass the relay chain into 😅. This could be a good candidate for more documentation 🙏.

**Comment by wirednkod** [comment]
> Dug into how smoldot work and found that there's a `potentialRelayChains` field that you need to pass the relay chain into 😅. This could be a good candidate for more documentation 🙏.

This is actually well documented in smoldot side: https://smol-dot.github.io/smoldot/doc-javascript/interfaces/AddChainOptions.html#potentialRelayChains

**Comment by tien** [comment]
Yep, that's where I found the info for it :p

It won't be obvious to someone who is completely new to polkadot though, so would be nice just including some parachain snippet in the docs.
