### ISSUE TITLE
Intermittent infinite loop when initiating multiple chains at the same time

### ISSUE THREAD

**Issue by tien** [polkadot-api/polkadot-api#620]
While building a multichain DApp, it occasionally enters an infinite loop if multiple chains are initiated at the same time. This appears to be some sort of race condition, investigating further now.

**Comment by josepot** [comment]
if you could provide us with a minimal repro that would be greatly appreciated 🙏

**Comment by tien** [comment]
Yep, I'm trying to narrow down exactly what happened. Hopefully will be able to come up with a somewhat consistent reproduction.

**Comment by tien** [comment]
So did some digging and the issue is due to 2 problems:
- PAPI not accounting for potential dead loop from restarting the connection, which #623 is trying to resolve
- Smoldot throwing a `AlreadyDestroyedError`, which should not happen if `remove` hasn't been called on the `Chain` object, I've double-checked this and this isn't implicitly called by PAPI anywhere, highly likely a smoldot issue.

**Comment by tien** [comment]
Update regarding the smoldot issue: I suspect the `AlreadyDestroyedError` happened due to this [line](https://github.com/smol-dot/smoldot/blob/2bd63792357fc8ffbbc5fce0d2932f9bf9dd504b/wasm-node/javascript/src/internals/client.ts#L306) in smoldot, where a "wasm-panic" error will clear the chain IDs, causing subsequent connection attempts to throw `AlreadyDestroyedError`.

**Comment by tien** [comment]
I was able to somewhat consistently reproduce the error and have raised an issue on Smoldot side: smol-dot/smoldot#1934
