### ISSUE TITLE
support Encointer as known-chain

### ISSUE THREAD

**Issue by brenzi** [polkadot-api/polkadot-api#631]
I tried to do a PR already, but I'll need info on how to generate the chain spec with `lightClientState` and possibly hints on what needs to be done to support Encointer

our chainspec can be found here, but it features genesis, not light client state
https://github.com/encointer/encointer-parachain/blob/master/node/res/encointer-kusama.json

**Comment by josepot** [comment]
> but it features genesis, not light client state 

actually, light client state is only relevant for relay-chains.

The only thing that we should change is the fact that the `genesis.raw` should be replaced with the `genesis.stateRootHash`. I will open a PR soon with this change.
