### ISSUE TITLE
Support u64 block number on signed extensions

### ISSUE THREAD

**Issue by rflechtner** [polkadot-api/polkadot-api#643]
PAPI currently hard-codes the assumption that block numbers have a `u32` data type in utils relating to signed extensions:
https://github.com/polkadot-api/polkadot-api/blob/03f1ccb10b163c9a98bcf2dca6aa50ae28037278/packages/client/src/tx/signed-extensions/utils.ts#L12-L15

This breaks fee estimation and transaction signing for all KILT chains, which use `u64` block numbers.

As a quick check if there are additional issues with support for u64 block numbers I successfully tried patching this logic to:
```js
const genesisHashStorageKey = Storage("System")("BlockHash", noop, [
  u64,
  Twox64Concat
]).enc(0n);
```
Transaction signing and fee estimation works this way.

**Comment by josepot** [comment]
> This breaks fee estimation and transaction signing for all KILT chains, which use `u64` block numbers.

TBH we never thought that a chain would choose anything other than a `u32` as a block-number type. However, this is 100% fixable. We will tackle before the end of the week.

Although, do you really think that humanity will last that long? 😅 🙈

**Comment by rflechtner** [comment]
> Although, do you really think that humanity will last that long? 😅 🙈 

Frankly, I don't know what we were thinking, and that choice has a history of breaking all sorts of tooling for us.

But it's awfully hard to undo unfortunately...
