### ISSUE TITLE
Insane startup memory usage due to esbuild issue

### ISSUE THREAD

**Issue by mutantcornholio** [polkadot-api/polkadot-api#654]
After upgrading PAPI on faucet, our node instances started to get instakilled by OOM. 

Heapdumps revealed that when using esbuild's binary loader, `Uint8Array`'s are being processed incorrectly, which temporary allocates about x200 if it's size, trying to define a property for each byte of array.  
Those properties get swiftly cleaned by GC, leaving us with normal memory usage.

In our case, that `Uint8Array` is `metadataTypes` [here](https://github.com/polkadot-api/polkadot-api/blob/75895134fed6cf897c3e9de38b6fccdb9798fddf/packages/codegen/src/generate-descriptors.ts#L303).

I've created [an issue](https://github.com/evanw/esbuild/issues/3894) in esbuild, but maybe it's possible to change the way we import `metadataTypes` to get around the issue faster then they'll release a fix?  
For example, store it as hex and convert to binary after the import.

**Comment by carlosala** [comment]
I think it probably makes sense to wait for esbuild guys ping. Let's see what they say. Thanks for the report!
