### ISSUE TITLE
How to work with anonymized types e.g the response of `Referenda.ReferendumInfoFor`

### ISSUE THREAD

**Issue by Tbaut** [polkadot-api/polkadot-api#658]
Hello there, it's me with a new question :)
I'm working with the results of `api.query.Referenda.ReferendumInfoFor` and I'm having issues typing this correctly.
For the context, I'm with React and willing to assign the result of `getValues` to a state.

I figured the type is anonymized, and is called `Ickru3l29veuqe`:

```ts
export type Ickru3l29veuqe = AnonymousEnum<{
    "Ongoing": Anonymize<I1a5mjgnoq33cs>;
    "Approved": Anonymize<Ini94eljn5lj8>;
    "Rejected": Anonymize<Ini94eljn5lj8>;
    "Cancelled": Anonymize<Ini94eljn5lj8>;
    "TimedOut": Anonymize<Ini94eljn5lj8>;
    "Killed": Anonymize<number>;
}>;
```

I guess it's not a good idea to use this directly. I tried still, together with `GetEnum` but I've no idea where I'm going and TS complains all over. What's the best way to deal with such types?

Some more context

```ts
  const [refInfo, setRefInfo] = useState<any[]>([])
  // I need to type this                 ^^^^^

  useEffect(() => {
    const refParams = refsVotedOn.map(([id]) => [id]) as [number][]

    api.query.Referenda.ReferendumInfoFor.getValues(refParams)
      .then((res) => {
        if (!res.values) return

        setRefInfo(res.filter((r) => !!r))
      })
      .catch(console.error)
  }, [api, refsVotedOn])
```

**Comment by josepot** [comment]
Also notice that the type intellisense should make things fairly straightforward (once you know that these types exist, of course):

https://github.com/user-attachments/assets/8a3e9b3a-dbd6-465a-bc0e-9d573490c092

**Comment by Tbaut** [comment]
Wow, this is beautiful, sorry to have missed it in the docs, and thank you so much!
This is absolutely an info that could be mentioned a little higher in the docs I'd say. In a "Good to know", together with `Multiaddress.id("SS58")` for instance. The enum type discrimination that is present above this section, and that you showed me the other day as well. Now I know it, but it's really helpful.

**Comment by josepot** [comment]
> Wow, this is beautiful, sorry to have missed it in the docs, and thank you so much!

Yeah! I'm discussing with the team the best way to explain these things to new comers. I think that we will record a short and to the point video with all these things and we will put it in the main page of the docs with a "Please watch this to get started" or something like that... I'm open to other ideas

**Comment by wirednkod** [comment]
I am very much "Aye" on creating a dotschool step by step guide on PAPI (already prepared part of it) on how to install, setup for 2 chains, and then use the typings. Let me know if you are positive on that, and what are the best parts that should be added in it - and once created we can add it in the papi.how as official "starter" guide

**Comment by Tbaut** [comment]
I think video is a good idea, but:
- not everyone likes videos (I for one am not really a fan)
- it's not indexed in the search
- it quickly becomes outdated and it's hard to update, or even to spot that it's outdated

Thinking about the psychology behind the reason I missed it: in this particular case, I think it's because it is in a area where I thought it's not where I'd find information that is relevant to me any more. I've been on this page, read the "SS58String", "Enum", "HexString", then went super quickly over Binary, and left, as I though "ok I got the concept, the rest will be similar", effectively missing the last part "Interface types". Now of course, that's 1 case, many may read it.

I think that a section with very useful how-tos could help:
- get constants
- get query (with dynamic types)
- get accounts 
- sign a tx (with account + a type such as MultiAddress or SS58)
