### ISSUE TITLE
Ende to end example

### ISSUE THREAD

**Issue by BenWhiteJam** [polkadot-api/polkadot-api#661]
Is there an end-to-end example to get PAPI to run and fetch something?

**Comment by voliva** [comment]
In our docs we have a couple of links to existing examples or complete open-source dApps with PAPI, along with a quickstart guide to have something running: https://papi.how/getting-started

Currently as examples we have [khopswap](https://github.com/kheopswap/kheopswap) and [papi-teleporter](https://github.com/polkadot-api/react-teleport-example), and we will soon add a new one from the recent hackathon we participated in Berlin.

Closing, no action required. Please let me know if we should reopen it.

**Comment by BenWhiteJam** [comment]
Okay let me explain E2E example, "the death simple thing that you could show anybody in the world with a terminal installed on their computer in under 1 hour, no compromise excepted!".

1.) https://papi.how/getting-started/
80% there; if I copy-paste everything on this page and run it, I don't see anything on my terminal.

2.) https://github.com/kheopswap/kheopswap
the commands in the readme get me this error on a first trial:
<img width="802" alt="Screenshot 2024-08-26 at 19 03 46" src="https://github.com/user-attachments/assets/5a31e20b-28d0-433a-b8ca-5babe06f0026">

3.) https://github.com/polkadot-api/react-teleport-example
No readme, so I need to figure out how to get started in the first place.

**Comment by josepot** [comment]
you do realize that this library is meant for developers, right?

**Comment by BenWhiteJam** [comment]
Noted*
