### ISSUE TITLE
toBlockInfo: Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-api/polkadot-api#671]
## Description
The `toBlockInfo` function is occasionally called with `undefined` as its argument, leading to a `TypeError` when attempting to destructure the right side of the assignment. This error occurs randomly and may take a few minutes or hours to manifest.

https://github.com/polkadot-api/polkadot-api/blob/a23688b6c80ec48b5719e34b15242925664bce54/packages/observable-client/src/chainHead/chainHead.ts#L240.

## Steps to Reproduce
1. Connect papi to `wss://westend-people-rpc.polkadot.io`
2. Leave the script running until the error appears (may take a few minutes or hours)

## Environment
- papi version: 1.1.0
- Bun version: 1.1.26 (Linux x64 baseline)

## Error Message

```log
17 | import { getValidateTx } from './validate-tx.mjs';
18 | import { withDefaultValue } from '../utils/with-default-value.mjs';
19 | import { concatMapEager } from '../utils/concatMapEager.mjs';
20 | import { shareLatest } from '../utils/shareLatest.mjs';
21 | 
22 | const toBlockInfo = ({ hash, number, parent }) => ({
                         ^
TypeError: Right side of assignment cannot be destructured
      at toBlockInfo (/usr/src/app/node_modules/@polkadot-api/observable-client/dist/esm/chainHead/chainHead.mjs:22:21)
      at /usr/src/app/node_modules/@polkadot-api/observable-client/dist/esm/chainHead/chainHead.mjs:138:20
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/scanInternals.js:14:21
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/distinctUntilChanged.js:18:28
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subject.js:69:34
      at errorContext (/usr/src/app/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subject.js:59:24
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/ReplaySubject.js:45:31
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:26
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:24
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/scanInternals.js:17:38
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:28:28
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:26
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:28:28
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21
      at /usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18

Bun v1.1.26 (Linux x64 baseline)
error: script "start" exited with code 1
```

**Comment by ryanleecode** [comment]
i'm trying to repro again and i'll paste the `withLogsProvider` logs here shortly

**Comment by ryanleecode** [comment]
Somewhere in here: https://gist.github.com/ryanleecode/f38f9de19e517994376dd89730535c5c

**Comment by carlosala** [comment]
Hey @ryanleecode, thanks for the report! Can't reproduce though with those logs, everything seems to be normal. Could you share your exact code? Thanks!
For the record, I tried just to subscribe to the bestBlocks with your logs and everything seems normal.
```typescript
import { createClient } from "polkadot-api"
import { logsProvider } from "polkadot-api/logs-provider"

const logs = (await Bun.file("./papi-671.log").text()).trim().split("\n")
const client = createClient(logsProvider(logs))
client.bestBlocks$.subscribe((b) => console.log(b))
```

**Comment by josepot** [comment]
> 2\. Leave the script running until the error appears (may take a few minutes or hours)

which script? 🙏

The logs are not that useful, unless we know what the script was actually doing.

**Comment by ryanleecode** [comment]
sorry no script, i meant just run the client. 

I just have it idling while being connected to chainhead.

**Comment by josepot** [comment]
> sorry no script, i meant just run the client.

the top level client? So basically, the script that @carlosala shared but without the last line, yeah?

**Comment by ryanleecode** [comment]
Yes exactly. 

It looks like a race/mutability issue. I think it can be solved by just deep cloning during this `map` so the data is always immutable when its emitted 

https://github.com/polkadot-api/polkadot-api/blob/a23688b6c80ec48b5719e34b15242925664bce54/packages/observable-client/src/chainHead/streams/pinned-blocks.ts#L228

**Comment by ryanleecode** [comment]
repro successful here w/ `logsProvider`

https://github.com/ryanleecode/papi-test-671/actions/runs/10602391405/job/29384321061

**Comment by josepot** [comment]
After having had a close look into this, I can see that this is not a problem with PAPI, but rather an issue with the RPC node which is not spec-compliant.

A block that has never been announced is being reported as the best block and 2 messages later the new-block event is emitted:

```
