### ISSUE TITLE
TS version 4.8.3 unable to find path 

### ISSUE THREAD

**Issue by decentration** [polkadot-api/polkadot-api#676]
# Issue:

when following the docs, there was an issue at this path:

```
import SmWorker from "polkadot-api/smoldot/worker?worker";
``` 

## error:
```
Cannot find module 'polkadot-api/smoldot/worker?worker' or its corresponding type declarations.ts(2307)
```

## Reproduction:

`git clone https://github.com/decentration/sm-worker-ts-4.8.3-repro.git`
`npm i`
`// check src/smworker.ts`

## Solution:

bump Typescript to >5.

## TODO:

update docs please! 👯

**Comment by carlosala** [comment]
Hi! The problem here is that typescript v4.x does not support `moduleResolution: "bundler"`. I see many other errors than the one you show. Actually, it can import the vite worker as expected with your repro.
If you want to use `moduleResolution: "bundler"` then you need to update typescript, and this has nothing to do with `polkadot-api`.

**Comment by josepot** [comment]
> Hi! The problem here is that typescript v4.x does not support `moduleResolution: "bundler"`. I see many other errors than the one you show. Actually, it can import the vite worker as expected with your repro. If you want to use `moduleResolution: "bundler"` then you need to update typescript, and this has nothing to do with `polkadot-api`.

The point of this issue was precisely that the Requirements section of the docs should mention the minimum TS version that we require.

**Comment by carlosala** [comment]
We added the minimum required version [in the docs](https://papi.how/requirements). It turns out to be `5.2`, nevertheless it is for a different reason.
We recommend you update asap to typescript `>5.2`.
Thanks for the report! 😉
