### ISSUE TITLE
`view-builder` incorrectly handle recursive shape

### ISSUE THREAD

**Issue by tien** [polkadot-api/polkadot-api#679]
Recursive shapes are resolved as void, for example, see the below shape for Utility pallet calls

<img width="490" alt="image" src="https://github.com/user-attachments/assets/558195ad-b02f-40bd-a55e-c52571e0b390">

Reproduction can be observed by logging the following `callsEntry` variable here: https://github.com/tien/dot-console/blob/7663b0cfd18ea617ed7e5078180840a44a8b4a04/src/routes/_layout/extrinsics.tsx#L80 (`feat/improved-extrinsic-builder` branch) and select `Utility` on the "extrinsics" page.

**Comment by josepot** [comment]
I'm super sorry that it took me so long to get to this. I just was able to reproduce it on my own. I'm fairly confident that we should have a fix very soon.

**Comment by josepot** [comment]
In the end, this was the silliest thing ever 🙈. Thanks for reporting this and sorry about the fact that it took so long for us to fix it!

**Comment by tien** [comment]
Awesome! Thanks for looking into and fixing this 🙏
