### ISSUE TITLE
Create a transaction from SCALE encoded call data

### ISSUE THREAD

**Issue by Tbaut** [polkadot-api/polkadot-api#682]
Hi there,
Currently, my app allows users to paste encoded call data (a hex string) and I create a call from it.
I couldn't figure out how to go from SCALE hex to a `Transaction` type.

Ideally, I'd have a constructor such as `Transaction.fromHex('0xababab')` but let me know if I missed it.

**Comment by carlosala** [comment]
Unfortunately, we don't have an option at this point to do so. This is a duplicate of #527.
We made an attempt at #554, but we decided not to proceed until we had other use cases.
I think we should have it, we'll work on it 👍🏻

**Comment by Tbaut** [comment]
Oh, sorry I didn't see the previous issue about it.
It's indeed a blocker for me unfortunately because the encoded call data is what gets stored on chain, or off-chain by multisig users.

For me to show to multisig signatories what call they are actually signing (instead of just the hash), either they paste the call data, or when possible I fetch it from RPC node by asking for the transactions included in a previous block, I can then decode it, and they can verify what they're about to sign.

I'll close and follow the other issue :pray:
