### ISSUE TITLE
A minimal TS-only template? 

### ISSUE THREAD

**Issue by kianenigma** [polkadot-api/polkadot-api#688]
I am not great at the latest TS compiler setup, and would love to have a template repo that I can clone, and write scripts in it. No web components or React needed. 

So, similar to https://github.com/polkadot-api/webpack-example, but perhaps raw TS?

I made one for PJS years ago for the same purpose: https://github.com/kianenigma/polkadot-js-api-ts-template

**Comment by carlosala** [comment]
If you fancy using `Bun` (highly recommended) you can just follow:

```shell
mkdir my-scripts; cd my-scripts
bun init # answer yes to all
bun install polkadot-api
# just go and edit index.ts!
```

Nevertheless, having a boilerplate would be nice, I agree!

**Comment by kianenigma** [comment]
noice, I also found https://github.com/Tbaut/papi-node. 

I think enough to close the issue :) 

Recommendation: add this in your README?
