### ISSUE TITLE
Dynamic client that supports unrestricted chain interactions

### ISSUE THREAD

**Issue by tien** [polkadot-api/polkadot-api#705]
The client currently uses a descriptor to perform a runtime check and throws an error if the descriptor doesn’t match what’s in the runtime. While this works for most DApps, since you generally want to run codegen against the specific chain you’re targeting, there are exceptions.

For specific use cases, like development tools (e.g. tien/dot-console#5), users may need to target any chain dynamically at runtime. In such cases, they depend on runtime introspection to interact with the chain, requiring a client that can function without a pre-generated or mismatched descriptor.

**Comment by josepot** [comment]
> For specific use cases, like development tools (e.g. [tien/dot-console#5](https://github.com/tien/dot-console/issues/5)), users may need to target any chain dynamically at runtime. In such cases, they depend on runtime introspection to interact with the chain, requiring a client that can function without a pre-generated or mismatched descriptor.

The top-level client is not meant for dev-tools like the dot-console. A developer console should use the libraries that the client uses internally, not the client itself.

**Comment by tien** [comment]
That’s a good point! However, I still believe there's value in having the ability to quickly get a dynamic client (without runtime type checks) directly from a URL. While this can already be achieved using the supporting libraries, it would essentially duplicate much of the code from `createTypedApi`. As far as I know, `createTypedApi` already supports dynamic interaction by simply disabling explicit runtime type enforcement (which should only require a few changes).

If this functionality doesn’t belong in the top-level client (which I agree with), it could be exposed elsewhere in PAPI. For example, the following:

```ts
type createTypedApi = <D extends ChainDefinition>(
  compatibilityToken: Promise<CompatibilityToken>,
  chainHead: ReturnType<ReturnType<typeof getObservableClient>["chainHead$"]>,
  broadcast$: (tx: string) => Observable<never>,
): TypedApi<D>;
```

Could be modified and exposed as:

```ts
export function createApi<D extends ChainDefinition>(
  chainHead: ReturnType<ReturnType<typeof getObservableClient>["chainHead$"]>,
  broadcast$: (tx: string) => Observable<never>,
  compatibilityToken: Promise<CompatibilityToken>
): TypedApi<D>;
export function createApi(
  chainHead: ReturnType<ReturnType<typeof getObservableClient>["chainHead$"]>,
  broadcast$: (tx: string) => Observable<never>
): UnTypedApi;

// Or even

export function createApi(client: SubstrateClient): UnTypedApi;
```

Let me know if this makes sense 🙏.
