### ISSUE TITLE
Export `CompatibilityToken`

### ISSUE THREAD

**Issue by Tbaut** [polkadot-api/polkadot-api#718]
Hey there, did you miss me already? :)
While I'm about to use it to make synchronous calls, I realize that I can't import the type `CompatibilityToken`.

> Module '"polkadot-api"' declares 'CompatibilityToken' locally, but it is not exported

did I miss something?

**Comment by carlosala** [comment]
Yep, you're right. It's not being exported. We should probably export it as a type, let's think about it. In the meantime,
```ts
Awaited<ReturnType<PolkadotClient["getTypedApi"]>["compatibilityToken"]>
```
gets the job done.

**Comment by voliva** [comment]
Yep, we definitely have to export it
