### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'methods')

### ISSUE THREAD

**Issue by mutantcornholio** [polkadot-api/polkadot-api#747]
We see this crash on Faucet in Westend:
<img width="970" alt="Screen Shot 2024-09-25 at 17 40 33" src="https://github.com/user-attachments/assets/b31a992f-1d67-45b1-bc42-10684e40aff9">

Currently running on 1.3.2
Also not happenning on Paseo

**Comment by carlosala** [comment]
This was solved in #794 (released on v1.6.1). Feel free to comment if you see this error again. Thanks!
