### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'number')

### ISSUE THREAD

**Issue by mutantcornholio** [polkadot-api/polkadot-api#748]
We get following crash on Paseo:
<img width="998" alt="Screen Shot 2024-09-26 at 17 21 50" src="https://github.com/user-attachments/assets/4c4cc4a8-3147-470c-a4ca-2933d889d01e">

Currently running on 1.3.2

**Comment by Tbaut** [comment]
A workaround is to add it with websocket `papi add pas -w wss://paseo.rpc.amforc.com`
I think this is linked to the default endpoint. I don't have any issue with the one above.

**Comment by carlosala** [comment]
This error should be solved as with `withPolkadotSdkCompat`. Closing for the moment, please comment if it keeps reproducing in `1.6.1`.
