### ISSUE TITLE
CLI command not working on windows

### ISSUE THREAD

**Issue by hoangdevnull** [polkadot-api/polkadot-api#773]
I believe I can successfully run the papi CLI on MACOS, but I have encountered a problem when trying to run the command on Windows. The current workaround is to commit the dist folder to github, but beyond that I would like to know why this is happening and any fixable for this. 

![image](https://github.com/user-attachments/assets/de2a55fb-4437-4534-a5ba-46cbe1227cb8)

![image](https://github.com/user-attachments/assets/f368ef66-9b46-459d-9bf7-d760ee4a0739)

Reproduce environment: 

- Windows 11
- Node version: 20.6.0
- polkadot-api version: 1.3.2

**Comment by voliva** [comment]
This is due to an [issue on tsup](https://github.com/egoist/tsup/issues/1150), the bundler we use to build the descriptors. The underlying issue is they use `tinyglobby`, which assumes posix separators.

There's a workaround, which is to change the separators from windows to posix. Fix incoming.

**Comment by windev1108** [comment]
I think this is a related problem after solving the old problem, I was able to run CLI command but then I got `**innerDecoder is not a function**` error when reading account number when subscribing balance,  I would like to know why this is happening and any fixable for this
<img width="520" alt="issue 1" src="https://github.com/user-attachments/assets/87e67aaa-5a25-453d-a020-5ecc93f62a30">
<img width="360" alt="issue 2" src="https://github.com/user-attachments/assets/e2d907ab-d1db-4958-aa2d-18fa312a06ff">

**Comment by josepot** [comment]
> I think this is a related problem after solving the old problem, I was able to run CLI command but then I got `**innerDecoder is not a function**` error when reading account number when subscribing balance, I would like to know why this is happening and any fixable for this

Could you please provide more context? (polkadot-api version, os that you are using, etc). A GH repo with a repro would be ideal... Otherwise, there is no way for us to figure out what's happening. Thanks!

Also, what makes you think that this is a related issue? I really don't seen how this could be related... Although, maybe there is something that I'm missing here.
