### ISSUE TITLE
docs: quick recipes

### ISSUE THREAD

**Issue by brunopgalvao** [polkadot-api/polkadot-api#778]
I would like to see some quick recipes that I can copy/paste and tweak.

For example:

![Screenshot 2024-10-09 at 2 59 43 PM](https://github.com/user-attachments/assets/d57b28b5-6e06-4b6f-a472-bcc19138dd3a)

Specifically, I would like a cross-chain example e.g. `limitedReserveTransferAssets` from AH to Pop that serves as a good base for a cross-chain example.

e.g. https://substrate.stackexchange.com/a/11969/29

**Comment by josepot** [comment]
[Done](https://papi.how/recipes/simple-transfer)!
