### ISSUE TITLE
Cannot estimate fee for Moonbeam

### ISSUE THREAD

**Issue by tuul-wq** [polkadot-api/polkadot-api#807]
I'm trying to make a transfer in Moonbeam and before that I need to estimate the fee.
```js
  getTransferKeepAliveTx(api: TypedApi<typeof glmr>, destination: Address, amount: BigInt) {
    return api.tx.Balances.transfer_keep_alive({
      value: amount,
      dest: destination,
    });
  }

  // api is typed for Moonbeam
  // dest accepts HexString
  getTransferKeepAliveTx(api, '0x6F21E1C5234eC2DA8019632d4836fFCC2379DbA7', 1n);
```
Everything seems fine at this point, but when I do
```js
  tx.getEstimatedFees(destination);
  // or because it accepts Uint8Array or SS58String
  // which is not the case for "0x6F21E1C5234eC2DA8019632d4836fFCC2379DbA7"
  tx.getEstimatedFees(stringToU8a (destination));
```
It fails with error
```bash
OperationError: Execution failed: Execution aborted due to panic: panicked at /build/runtime/moonbeam/src/lib.rs:1549:1:
Bad input data provided to account_nonce: Input buffer has still data left after decoding!
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x6a1c - <unknown>!rust_begin_unwind
    1: 0x36d0 - <unknown>!core::panicking::panic_fmt::h7d22643b0becf577
    2: 0x594e5a - <unknown>!AccountNonceApi_account_nonce
    at Object.next (polkadot-api.js?v=ce55e648:2380:17)
    at Object.next (polkadot-api.js?v=ce55e648:2313:58)
    at Object.onAllFollowEventsNext [as next] (polkadot-api.js?v=ce55e648:2566:30)
    at Object.next (polkadot-api.js?v=ce55e648:2313:58)
    at onMessage (polkadot-api.js?v=ce55e648:2738:23)
```

Also I've looked into `getEstimatedFees` and "Sr25519" looks wrong for Moonbeam signer, doesn't it?
```js
const getPaymentInfo = async (from2, _options) => {
      const fakeSigner = getPolkadotSigner(
        from2 instanceof Uint8Array ? from2 : accountIdEnc(from2),
        "Sr25519",
        getFakeSignature
      );
      // ... rest of the function
};
```

`polkadot-api` version: 1.6.1

**Comment by josepot** [comment]
Thanks a lot for reporting this issue.

I didn't know that moonbeam only accepts ECDSA signatures. I thought that when it came to creating extrinsics, their extrinsics were going to have the same shape as the rest of the PolkadotSDK chains. However, that it's not the case.

In the rest of PolkadotSDK chains the input of the fields "address" and "signature" is a variant, but not in Moonbeam. We will have to tweak things a bit to adapt to this kinds of extrinsics. It shouldn't take us long to fix this, though. I'm fairly confident that we will be able to have a fix by early/mid next week.

**Comment by josepot** [comment]
#817 fixes this. However, please [read this](https://github.com/polkadot-api/polkadot-api/discussions/819) carefully. 🙏

**Comment by tuul-wq** [comment]
Thanks a lot for resolving the issue 🙌
