### ISSUE TITLE
Can not query data from Parachain

### ISSUE THREAD

**Issue by hoangdevnull** [polkadot-api/polkadot-api#810]
Hi I'm try to use this library with hydration parachain. Basically, I try to get the token free through `Tokens` pallet but I'm unable to get that information. 

The code: 

```typescript
const client = createClient(getWsProvider('wss://hydradx-rpc.dwellir.com');
const api = client.getTypedApi(hdx);

 api.query.Tokens.Accounts.watchValue(address, token.assetId, 'best').subscribe((res) => {
      const balance = res.free - res.frozen;
      console.log({balance});
    });
```

Result logs: 

![image](https://github.com/user-attachments/assets/eac215be-3f2a-4fa8-8ced-987e8d95fcfc)

**Comment by josepot** [comment]
[Unable to reproduce](https://stackblitz.com/edit/vitejs-vite-lqopgn?file=src%2Fmain.ts).

**Comment by hoangdevnull** [comment]
Thank you for providing the reproduction. It appears that I may be utilising an incorrect version of the Polkadot SDK. I have found that using the `withPolkadotSdkCompat` is effective.
