### ISSUE TITLE
change paseo ss58Format from 42 to 0

### ISSUE THREAD

**Issue by hitchhooker** [polkadot-api/polkadot-api#833]
change paseo ss58Format from 42 to 0

**Comment by josepot** [comment]
Dup of #767 

TL;DR: this is not a PAPI issue. It's an issue with a misconfiguration of the Paseo RPC providers.

**Comment by josepot** [comment]
Actually, I just noticed that [we also got the chainspecs wrong](https://github.com/polkadot-api/polkadot-api/issues/767) as we copied them from their repo...  🤦 So, I'm reopening this issue.

**Comment by hitchhooker** [comment]
this issue was just me spotting wrong value when readinf configs so absolute nothing burger.
not sure if it had any influence at all. i will be submitting coming days PR more bootnodes for paseo system parachains.
that said there is starting to be quite multiple states for bootnodes to be kept up to date(and more in future with expansion in the amount of clients) i wonder what would be most sustainable solution in terms of maintenance. ibp members provide the most of the bootnodes so I wonder should we provide repository/api of bootnodes with workflows to provide PRs injecting bootnodes on update. i have on my todo list to write more robust monitoring for bootnodes so could provide always functional state of bootnodes and get rid of those connection errs and penalize members providing invalid bootnodes.

i remember tomaka mentioning about some resolution for overcoming having bootnodes at all but i doubt this initiative has advanced much since?

would love to hear second opinion before i go ahead and propose such work and also if you have idea whats best way to spot if bootnode functions or not. this far we been just using polkadot client and its metrics but there is for sure better way to do this without 100mb binary.

**Comment by josepot** [comment]
> i wonder what would be most sustainable solution in terms of maintenance

Undoubtedly, [RFC-8](https://polkadot-fellows.github.io/RFCs/approved/0008-parachain-bootnodes-dht.html) is -by far- the best solution. However, despite the RFC having being approved, it has never been implemented 😞.
