### ISSUE TITLE
RPC methods in PAPI

### ISSUE THREAD

**Issue by nhussein11** [polkadot-api/polkadot-api#850]
Can this query be replicated by using PAPI? 

- `api.rpc.author.pendingExtrinsics`
- Reference - [https://polkadot.js.org/docs/substrate/rpc#pendingextrinsics-vecextrinsic](https://polkadot.js.org/docs/substrate/rpc#pendingextrinsics-vecextrinsic)

Tried looking at the docs, but I don't see a clear example of it

**Comment by voliva** [comment]
RPC methods are usually not standard and are not defined by the metadata, so papi can't add types and other features on them. But they are still accessible through `client._request`, the [client reference](https://papi.how/client) on the docs has a small example as part of the JSDoc:

```ts
  /**
   * This API is meant as an "escape hatch" to allow access to debug endpoints
   * such as `system_version`, and other useful endpoints that are not spec
   * compliant.
   *
   * @example
   *
   *   const systemVersion = await client._request<string>("system_version", [])
   *   const myFancyThhing = await client._request<
   *     { value: string },
   *     [id: number]
   *   >("very_fancy", [1714])
   *
   */
  _request: <Reply = any, Params extends Array<any> = any[]>(
    method: string,
    params: Params,
  ) => Promise<Reply>
```

by default it falls back to `any` types, but you can still use its generics to add types if you're certain they have specific ones.
