### ISSUE TITLE
Typescript Compilation errors when updating metadata and renerating descriptors

### ISSUE THREAD

**Issue by 71walceli** [polkadot-api/polkadot-api#893]
when generating code or updating metadata via `papi update` or `papi generate`, package seems to be generated and installed, but it produces lots of compile errors.

**Expected behaviour**: Generated code should be installed with no errors.
**Obtained result**: Code seems to get updated, but will produce lots of errors.

```
.papi/descriptors/src/westend.ts(2522,8): error TS2314: Generic type 'StorageDescriptor' requires 4 type argument(s).
.papi/descriptors/src/westend.ts(2528,19): error TS2314: Generic type 'StorageDescriptor' requires 4 type argument(s).
.papi/descriptors/src/westend.ts(2536,23): error TS2314: Generic type 'StorageDescriptor' requires 4 type argument(s).

Compilation done with 1666 errors
bun install
[3.61ms] ".env"
bun install v1.1.30 (7996d06b)

+ @polkadot-api/descriptors@.papi/descriptors

1 package installed [421.00ms]
```

I updated dependencies as suggested https://github.com/tien/reactive-dot/issues/405#issuecomment-2533574353, but still would seem to get same issue generating metadata, and linked issue as well. Version testd with is 1.7.7.

**Comment by carlosala** [comment]
Hi! Yeah, that's a known bug, not ours, though, but from `pnpm`. Running `pnpm dedupe` should solve it. Please comment on whether it worked or reopen it otherwise.
Thanks for the report!

**Comment by 71walceli** [comment]
Seems solved now. I deleted the Docker container, rebuilt the image, and nuked all deps again. DOn't know when all started working fine. in fact, I don't have the issue remported for `reactive-dot`, descriptsrs built correctly, no errors. Thanks so much for the advice and support!

**Comment by 71walceli** [comment]
I did `bun update`, which updated everything, as well as others. But that procuced some errors with postcss init when launckhing dev container.  So I reverted the commit, picking and cloosing packages to revert. and that seems to have fixed it.
